### ISSUE TITLE
docker-compose: Crashes on first access

### ISSUE THREAD

**Issue by lionkor** [itsalb3rt/cloudcsv#40]
**Describe the bug**
Docker Compose version 2.9.0
Docker version 20.10.17, build 100c70180f

When running docker-compose up, and accessing the website it hosts, it crashes with the following error:

```
cloudcsv-cloud-csv-web-1  | [Tue Aug 16 2022 10:39:34 GMT+0000 (UTC)]  "GET /" "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0"
cloudcsv-cloud-csv-web-1  | /usr/local/lib/node_modules/http-server/lib/core/index.js:246
cloudcsv-cloud-csv-web-1  |           stream = Readable.from(bytes)
cloudcsv-cloud-csv-web-1  |                             ^
cloudcsv-cloud-csv-web-1  | 
cloudcsv-cloud-csv-web-1  | TypeError: Readable.from is not a function
cloudcsv-cloud-csv-web-1  |     at serve (/usr/local/lib/node_modules/http-server/lib/core/index.js:246:29)
cloudcsv-cloud-csv-web-1  |     at fs.stat (/usr/local/lib/node_modules/http-server/lib/core/index.js:419:13)
cloudcsv-cloud-csv-web-1  |     at FSReqWrap.oncomplete (fs.js:171:5)
```

**Comment by itsalb3rt** [comment]
Thanks for letting me know, I'll be checking and correcting.

**Comment by itsalb3rt** [comment]
The problem was the version of node, now, is ready! Thanks! 🙌
